services:
  mariadb:
    image: mariadb:11
    container_name: checkpoint_explorer_mariadb
    environment:
      MARIADB_USER: explorer
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: checkpoint_explorer_db
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  checkpoint-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkpoint_explorer_app
    environment:
      APP_DATABASE_URL: mysql://explorer:password@mariadb:3306/checkpoint_explorer_db
      STRATA_FULLNODE: "https://rpc.testnet-staging.stratabtc.org/"
      APP_FETCH_INTERVAL: 5
    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_healthy
    command: ["./checkpoint-explorer"]

volumes:
  mariadb_data:
